sudo: required
services:
  - docker
env:
  global:
    - REGISTRY_USER=leoll2android
    - secure: "gd/CuPD4VfvddhQJqgmJ9DZPpF/KFOhnqA3RlmGO4c+tbNIkqkWuNzZob3sOOEBtd+K4UTwqwS9nKoDVxzVz1teS4N2zpnrQhq8Lh4M7MUGj+NE21Dq+cWF9/ONYCKMqoui9us/E9nlIJMDUGyAM+m2zm7zjJugXSRn4WSt6nEnnmskHBfiAa4tWlMRoy0CySbG/8f35vg4zwTKwXFFDc7DKeYreuPz+ATApM4Yik9kro66mkwH4Hfeu7IM1UiE1CXcQMHMDktnZGEyGYCfKe27g3WV928ZPn0GE2HSPfazeiE238CU6HFAnJ9ID9faB19myfIHdfCFQL4cpIOHOj2PjFP1dFy/MOhhFCtJ6aOeEfRDFJL+GV25oa4r1OSrvS+BOfpvKLhNYn++V1OMDqbuVqDt5GMsfZ3w8nqZ+ZWjMkvrkCUqszZYDNLIYvrvxn5Hz7oyF6XMQ5S4YT0jZ3oHShx4JGFZXojvKmWQln7LQU159WtNrnLnNP1WGrzP5Ua+euUCgWYE8vDB8LzLVg4ia9GbdDHgW3jqj4f5tG6qgNxXiyhzoXFhRVVfnFcEj4yokUdrolqoFBSjm17h9BRNw7E/K87YIw61anVv8IJd5mP7HyW1diV684w+0yJtAMMtJlinTAmgY4c6WQPObvyxGO6NKbooClEx1EYe0RAk="

before_script:
  - docker pull leoll2org/git-fat-image || true

script:
  - docker build --pull --cache-from leoll2org/git-fat-image --tag leoll2org/git-fat-image .
  - docker run leoll2org/git-fat-image bash -c "git clone --depth 1 -b $TRAVIS_BRANCH https://github.com/leoll2/git-fat && cd git-fat && cp git-fat /usr/local/bin/git-fat && ./run_test.py"

after_script:
  - docker images

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  provider: script
  script: docker push leoll2org/git-fat-image
  on:
    branch: master
